### ISSUE TITLE
쿠버네티스 첫걸음

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-k8s#1]
## 참고자료
 - [쿠버네티스-플레이-그라운드](https://labs.play-with-k8s.com)
 - [강좌-따배쿠-쿠버네티스-시리즈](https://www.youtube.com/playlist?list=PLApuRlvrZKohaBHvXAOhUD-RxD0uQ3z0c)
 - [k3s-공식-문서](https://docs.k3s.io/)

## ConfigMap
 - kubectl create configmap ...
 - case1. 명령으로 즉시 생성
 ![image](https://github.com/kwonslog/how-to-use-k8s/assets/65941166/36b54fea-0c44-4c42-84ef-e54cff8c588a)
![image](https://github.com/kwonslog/how-to-use-k8s/assets/65941166/342e495a-30d4-4ab7-9ae6-1c704254f291)
- case2. 파일로 생성. 실행은 kubectl apply -f 파일명
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  key1: value1
  key2: value2
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: key1
    - name: KEY2
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: key2
```
- case3. env 와 envFrom 으로 사용하기
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  key1: value1
  key2: value2
---
...생략
    env:
    - name: KEY1
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: key1
    - name: KEY2
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: key2
```
```
...생략
    envFrom:
    - configMapRef:
        name: my-config
```

## Secret
- 비밀 정보나 중요한 설정 값을 안전하게 저장하고 관리하기 위한 리소스
- Base64로 인코딩되어 있어 일반적으로 비밀 정보를 저장하고 전송하는 데 사용
- configMap 과 사용하는 목적이 유사하다.

## Annotation
- 쿠버네티스에서 어노테이션(Annotations)은 레이블(Label)과 유사하게 메타데이터를 제공하는 키-값 쌍이지만, 그 사용 목적과 적용 방법에서 차이가 있습니다.
- 어노테이션은 리소스를 식별하거나 선택하는 데 사용되지 않습니다.
- 어노테이션은 쿠버네티스 클러스터의 리소스에 대한 추가적인 정보를 제공하며, 이 정보는 구성 관리, 도구 통합, 사용자 정의 메타데이터 등 다양한 목적으로 활용됩니다. 

### nginx controller 설치
 - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/baremetal/deploy.yaml

## 기본 namespace 변경
 - cubectl config set-context --current --namespace=<변경할 네임스페이스>

## label
- 효과적인 서비스 관리를 위해 key:value 쌍으로 잘 구분할수 있게 작성해야 한다.
- 해당 값으로 Pod 를 컨트롤 할수 있다.

### pod 안에 labels 확인
- kubectl get pods --show-labels
### 대상 pod 안에 labels 추가
- kubectl label pod <대상파드명> <label key>=<label value>
  ex) kubectl label pod test-pod run=test
### 대상 pod 안에 labels 삭제
- kubectl label pod <대상파드명> <label key>-
  ex) kubectl label pod test-pod run-
### label 값으로 pod 찾기
- kubectl get pods --selector run=test

## Node Label
- Worker Node의 특성을 Label로 설정
### key 값으로 목록 보기
- kubectl get nodes -L kubernetes.io/hostname
![image](https://github.com/kwonslog/how-to-use-k8s/assets/65941166/6879e63b-c8dc-4f73-b153-03d900b3abc7)

## Deployment
- 롤링 업데이트를 위해 사용.
- Deployment 는 ReplicaSet을 컨트롤 한다.

### 롤링 업데이트 하기
  kubectl set image deployment <deploy_name> <container_name>=<new_version_image>

### 롤링 업데이트 이력보기
  kubectl rollout history deployment <deploy_name>
  kubectl rollout undo deploy <deploy_name>

## DaemonSet
 - 모든 모드에 1개씩 컨테이너를 공평하게 실행해 준다.
 - 로깅이나 모니터링 관련 기능을 모든 노드에 설치하는 용도로 사용 할 수 있다.
 - 롤링 업데이트도 지원한다.

## StatefulSet
- Pod 이름 및 볼륨(스토리지)를 유지해준다.
  Pod 가 실행되면 pod 이름 마지막이 해쉬값으로 처리되는데 이것을 사용하면 0 부터 순차적으로 넘버링 해 준다.
- 롤링 업데이트도 지원한다.

## Job
- Batch 처리에 적합한 컨트롤러로 Pod의 성공적인 완료를 보장
- 비정상 종료 시 다시 실행
- 정상 종료 시 완료

## Controller는 클러스터 내 리소스 상태를 관리하고 유지하며, 원하는 상태로 조정하여 안정적인 애플리케이션 배포 및 운영을 담당
 - Pod의 안정적인 배포, 롤링 업데이트, 자동 복구 및 스케일링과 같은 고급 배포 관리 기능을 제공

### ReplicationController : Pod의 개수를 보장.
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3  # 원하는 레플리카 수
  selector:
    app: webui  # 레플리카를 관리할 Pod을 선택하는 레이블 셀렉터
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui  # 생성되는 Pod에 할당할 레이블
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
        ports:
        - containerPort: 80
```
- kubectl get replicationcontrollers
- kubectl scale 명령으로 컨테이너의 개수를 늘리거나 줄일수 있다.
- 롤링 업데이트 가능 : kubectl edit 실행후 image 의 버전을 변경하고 컨테이너를 삭제 할 경우
  새롭게 실행되는 컨테이너는 수정된 image 의 버전으로 실행된다.

## ReplicaSet 은 더 많은 selector 옵션을 제공한다.
- matchLabels
- matchExpressions
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-rs
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
```
- 실행중인 컨테이너는 유지하고 ReplicationSet 만 삭제 하는 방법은 --cascade=false 옵션을 사용한다.
  이 경우 다시 ReplicationSet 을 실행하면 관리 대상으로 포함되기 때문에 labels 을 정할때 명확히 구분해서
  사용해야 혹시 모를 사건사고를 막을수 있다.

## pod 실행용 예제
cat > nginx.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
    - containerPort: 80
      protocol: TCP

### static Pod 
 - kubelet 데몬에 의해 해당 노드에서만 실행된다. 
 - .yaml 파일을 지정 경로에 둘 경우 자동으로 실행된다.
   마스터 노드에서 /etc/kubernetes/manifests 경로에 보면 etcd, api 서버 등 다수의 yaml 파일이 존재한다.

### 쿠버네티스 설정파일
 /var/lib/kubelet/config.yaml

### 쿠버네티스 static pod 기본경로(변경가능)
 /etc/kubernetes/manifests

## 컨테이너 리소스 설정
 - 컨테이너 실행에 필요한 최소치(requests) 최대치(limits) 를 설정한다.
 - 설정 단위에 주의한다.  
 - limits 만 설정할 경우 requests 도 동일한 값으로 설정된다.

  resources:
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: 1
      memory: 500Mi

## 환경변수 설정
  env:
  - name: MYVAR
    value: "testValue"

## 네임스페이스 안에 Pod 조회
- kubectl get pods -n [이름]

## 리소스 생성
- kubectl create -f [경로]

## 네임스페이스 생성
- kubectl create namespace [이름]

### apiVersion 확인하기
- kubectl explain pod

### 생성 정보를 yaml 형식으로 확인하기 
- kubectl create namespace oranage --dry-run -o yaml

### 네임스페이스 yaml 파일로 생성하기
- kubectl get namespaces
- kubectl create namespace orange --dry-run -o yaml > orange.yml
  kubectl create -f orange.yml

### 기본 네임스페이스 변경하기
- kubectl config set-context blue@k8s --cluster=kubernetes --user=kubernetes-admin --namespace=blue
- kubectl config use-context blue@k8s
- kubectl config view
